### ISSUE TITLE
http-gateway tests fail intermittently

### ISSUE THREAD

**Issue by glyn** [projectriff/riff#305] opened 2018-02-28 17:32 UTC
Example of the failure (from [CI](https://ci.projectriff.io/teams/main/pipelines/riff/jobs/build-component-images-dev/builds/14?)):
```
2018/02/28 17:19:30 Listening on :16911
•! Panic [0.007 seconds]
HTTP Gateway
/go/src/github.com/projectriff/riff/http-gateway/pkg/server/gateway_integration_test.go:35
  should accept messages and fire&forget [It]
  /go/src/github.com/projectriff/riff/http-gateway/pkg/server/gateway_integration_test.go:99

  Test Panicked
  runtime error: invalid memory address or nil pointer dereference
  /usr/local/go/src/runtime/panic.go:491

  Full Stack Trace
  	/usr/local/go/src/runtime/panic.go:491 +0x283
  github.com/projectriff/riff/http-gateway/pkg/server_test.glob..func1.5()
  	/go/src/github.com/projectriff/riff/http-gateway/pkg/server/gateway_integration_test.go:112 +0x271
  github.com/projectriff/riff/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc420492de0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	/go/src/github.com/projectriff/riff/http-gateway/pkg/server/server_suite_test.go:12 +0x64
  testing.tRunner(0xc4200102d0, 0x89dba8)
  	/usr/local/go/src/testing/testing.go:746 +0xd0
  created by testing.(*T).Run
  	/usr/local/go/src/testing/testing.go:789 +0x2de
  
------------------------------
••••••••••

Summarizing 2 Failures:

[Panic!] HTTP Gateway [It] should request/reply OK 
/usr/local/go/src/runtime/panic.go:491

[Panic!] HTTP Gateway [It] should accept messages and fire&forget 
/usr/local/go/src/runtime/panic.go:491

Ran 25 of 25 Specs in 0.043 seconds
FAIL! -- 23 Passed | 2 Failed | 0 Pending | 0 Skipped --- FAIL: TestHandler (0.04s)
FAIL
FAIL	github.com/projectriff/riff/http-gateway/pkg/server	0.087s
Makefile:10: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by glyn** [comment] 2018-02-28 17:36
The test should assert that an error did not occur so we get better diagnostics:
```
resp, _ := client.Do(req)
```

**Comment by glyn** [comment] 2018-02-28 17:43
The gateway integration test hits a null pointer when `client.Do()` returns a nil response. The test should assert that the error returned by`client.Do()` is `nil` so that we get to see the error (and avoid the null pointer problem) on future failures.

**Comment by glyn** [comment] 2018-02-28 17:44
Also, the basic problem is that the test is race-prone as designed because it starts the server and then goes on to use it without first ensuring the server is up. An easy way to solve this is to use Gomega’s `Eventually` construct.

**Comment by jchesterpivotal** [comment] 2018-02-28 19:23
I can confirm that it looks like a race condition. When I capture the error and panic with it, I get:

```
•! Panic [0.001 seconds]
HTTP Gateway
/go/src/github.com/projectriff/riff/http-gateway/pkg/server/gateway_integration_test.go:35
  should request/reply OK [It]
  /go/src/github.com/projectriff/riff/http-gateway/pkg/server/gateway_integration_test.go:72

  Test Panicked
  Post http://localhost:10785/requests/foo: dial tcp 127.0.0.1:10785: getsockopt: connection refused
  /usr/local/go/src/runtime/panic.go:491

  Full Stack Trace
  	/usr/local/go/src/runtime/panic.go:491 +0x283
  github.com/projectriff/riff/http-gateway/pkg/server_test.post(0x2a21, 0xc4204527b0, 0xd, 0xaa5ee0, 0xc420169ce0, 0xc42004d340, 0x4, 0x4, 0xc420169ce0)
  	/go/src/github.com/projectriff/riff/http-gateway/pkg/server/gateway_integration_test.go:141 +0x35a
  github.com/projectriff/riff/http-gateway/pkg/server_test.doRequest(0x2a21, 0x87ea26, 0x3, 0xaa5ee0, 0xc420169ce0, 0xc42004d340, 0x4, 0x4, 0x0)
  	/go/src/github.com/projectriff/riff/http-gateway/pkg/server/gateway_integration_test.go:120 +0xb4
  github.com/projectriff/riff/http-gateway/pkg/server_test.glob..func1.4()
  	/go/src/github.com/projectriff/riff/http-gateway/pkg/server/gateway_integration_test.go:86 +0x2be
  github.com/projectriff/riff/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc4202cf560, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	/go/src/github.com/projectriff/riff/http-gateway/pkg/server/server_suite_test.go:12 +0x64
  testing.tRunner(0xc4200102d0, 0x8a0768)
  	/usr/local/go/src/testing/testing.go:746 +0xd0
  created by testing.(*T).Run
  	/usr/local/go/src/testing/testing.go:789 +0x2de
  
------------------------------
2018/02/28 19:22:00 Listening on :16911
post() failed on client.Do()
•! Panic [0.001 seconds]
HTTP Gateway
/go/src/github.com/projectriff/riff/http-gateway/pkg/server/gateway_integration_test.go:35
  should accept messages and fire&forget [It]
  /go/src/github.com/projectriff/riff/http-gateway/pkg/server/gateway_integration_test.go:99

  Test Panicked
  Post http://localhost:16911/messages/bar: dial tcp 127.0.0.1:16911: getsockopt: connection refused
  /usr/local/go/src/runtime/panic.go:491

  Full Stack Trace
  	/usr/local/go/src/runtime/panic.go:491 +0x283
  github.com/projectriff/riff/http-gateway/pkg/server_test.post(0x420f, 0xc420452ae0, 0xd, 0xaa5ee0, 0xc4201f8460, 0xc420383340, 0x4, 0x4, 0xc4201f8460)
  	/go/src/github.com/projectriff/riff/http-gateway/pkg/server/gateway_integration_test.go:141 +0x35a
  github.com/projectriff/riff/http-gateway/pkg/server_test.doMessage(0x420f, 0x87e9e7, 0x3, 0xaa5ee0, 0xc4201f8460, 0xc420383340, 0x4, 0x4, 0xc42036c4e0)
  	/go/src/github.com/projectriff/riff/http-gateway/pkg/server/gateway_integration_test.go:124 +0xb4
  github.com/projectriff/riff/http-gateway/pkg/server_test.glob..func1.5()
  	/go/src/github.com/projectriff/riff/http-gateway/pkg/server/gateway_integration_test.go:110 +0x267
  github.com/projectriff/riff/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc4202cf740, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	/go/src/github.com/projectriff/riff/http-gateway/pkg/server/server_suite_test.go:12 +0x64
  testing.tRunner(0xc4200102d0, 0x8a0768)
  	/usr/local/go/src/testing/testing.go:746 +0xd0
  created by testing.(*T).Run
  	/usr/local/go/src/testing/testing.go:789 +0x2de
```

**Comment by ericbottard** [comment] 2018-04-05 13:48
Closing this, this has been taken care of if I'm not mistaken

**Closed by ericbottard** 2018-04-05 13:48 UTC
Labels: http-gateway
